name: Python application test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python scripts
      run: |
        python codigos/app.py
        python codigos/appBad.py
        python codigos/appGood.py
        python codigos/pandapp.py
        python codigos/timer.py
        # Asegúrate de actualizar las rutas de todos los scripts que deseas ejecutar.

